# Lab 33 - ICS/SCADA Syslog Configuration

# Receive UDP Syslog messages on port 514
module(load="imudp")
input(type="imudp" port="514")

# Receive TCP Syslog messages on port 514
module(load="imtcp")
input(type="imtcp" port="514")

# Store Lab 33 ICS/SCADA logs separately
if $programname == 'ics-simulator' then /var/log/ics-scada.log
& stop
