dev tun
proto udp
remote 127.0.0.1 1194
ifconfig 10.8.0.2 10.8.0.1
secret /home/ubuntu/SCADA-ICS-Security-101/Lab-18-Secure-Remote-Access-Basics/lab-static.key
cipher AES-256-CBC
data-ciphers AES-256-CBC
persist-key
persist-tun
verb 3
