dev tun
proto udp
port 1194
ifconfig 10.8.0.1 10.8.0.2
secret /home/ubuntu/SCADA-ICS-Security-101/Lab-18-Secure-Remote-Access-Basics/lab-static.key
cipher AES-256-CBC
data-ciphers AES-256-CBC
keepalive 10 60
persist-key
persist-tun
verb 3
